#!/bin/sh

node_modules/mocha/bin/mocha -R spec --compilers coffee:coffee-script/register \
  test/unit/                        \
  test/unit/token/                  \
  test/unit/tracking-buffer         \
  test/integration/
